# Generated by Django 4.1.1 on 2022-09-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ts',
            field=models.DateTimeField(null=True),
        ),
    ]
