# Generated by Django 4.1.1 on 2022-09-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Success'), (2, 'Processing'), (3, 'Failed')], default=0),
        ),
    ]
